name: "Get base"
description: "Get git base"
outputs:
  changed:
    description: the commit hash that represents the last change
    value: ${{ steps.changed.outputs.CHANGED }}
runs:
  using: composite
  steps:
    - id: changed
      name: "Get changed"
      run: |
        if ${{ github.event_name }} == 'pull_request'; then
          # Gets the name out of the path
          BASE_REF_NAME="$(echo ${{ github.base_ref }} | rev | cut -d / -f 1 | rev)"
          VAL=origin/"$BASE_REF_NAME"
        else
          # Gets previous commit hash
          VAL=$(git rev-parse @~)
        fi
        echo "::set-output name=CHANGED::${VAL}"
      shell: bash